## Python basics with Numpy

### 1. Building basic functions with numpy

#### 1.1 - sigmoid function, np.exp()

In [1]:
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [2]:
sigmoid(4)

0.9820137900379085

as input of this was a real number we barely use math library in deep learning as we mostly use matrices and vectors so numpy is prefered.

In [4]:
x = [1, 2, 3]
sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [ ]:
import numpy as np
x = np.array([1, 2, 3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


implementing sigmoid using numpy

In [7]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [11]:
sigmoid(3)
sigmoid(np.array([1, 2, 3]))

array([0.73105858, 0.88079708, 0.95257413])

#### 1.2 Sigmoid gradient:

as we need to compute gradients to optimize loss functions using backpropagation

In [12]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 -s)


In [13]:
sigmoid_derivative(45)

0.0

In [15]:
sigmoid_derivative(np.array([1, 2, 3]))

array([0.19661193, 0.10499359, 0.04517666])

#### 1.3 Reshaping arrays:
Two common numpy functions that are used in deep learning are np.shape() and np.reshape().

x.shape is used to get the shape of matrix/vector x.
x.reshape(...) is used to reshape x into some other dimension.

In [16]:
def image2vector(image):
    v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    return v

In [17]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
image2vector(image)

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])

#### 1.4 Normalizing rows:

In ML and DL we normalize our data. it often leads to a better performance as gradient converges faster after normalization.

In [25]:
def normalizeRows(x):
    # normalization is along the rows. (to have a unit length)
    # np.linalg.norm: NumPy Linear Algebra Norm
    x_norm = np.linalg.norm(x, axis=1, keepdims=True)
    print(x_norm.shape)
    x = x / x_norm
    return x

In [26]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
x.shape

(2, 3)

In [27]:
normalizeRows(x)
x.shape

(2, 1)


(2, 3)

here as the shape of x_norm is (2, 1) i.e. single value in whole row in each row (as expected) so broadcasting come into role when it is being divided by x.

In [28]:
def softmax(x):
    x_exp = np.exp(x) # for each row
    # now store sum of each exp of x values
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
    return x_exp / x_sum

In [30]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
softmax(x)

array([[9.80897665e-01, 8.94462891e-04, 1.79657674e-02, 1.21052389e-04,
        1.21052389e-04],
       [8.78679856e-01, 1.18916387e-01, 8.01252314e-04, 8.01252314e-04,
        8.01252314e-04]])

### 2. Vectorization:
dot/outer/elementwise.
Dot product (inner product): collapses two vectors into a single number.
Example:

[a,b]⋅[c,d]=ac+bd

Outer product: expands two vectors into a full matrix of pairwise products.
Example:

[a,b]⊗[c,d]=[a⋅c    b⋅c
	          a⋅d     b⋅d]
              
Outer product shows up in linear algebra (rank-1 matrices).

In ML, it’s used in covariance matrices, embeddings, attention mechanisms (query ⊗ key)

In [31]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

In [36]:
# classic dot product
tic = time.perf_counter()
dot = 0
for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.perf_counter()
print("Time taken" + str(1000*(toc-tic)) + "ms.")

# output product implementation
tic = time.perf_counter()
outer = np.zeros((len(x1), len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i, j] = x1[i]*x2[j]
toc = time.perf_counter()
print("Time taken" + str(1000*(toc-tic)) + "ms.")

# elment-wise product
tic = time.perf_counter()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.perf_counter()
print("Time taken" + str(1000*(toc-tic)) + "ms.")

# classic general dot product
w = np.random.rand(3, len(x1))
tic = time.perf_counter()
gdot = np.zeros(w.shape[0])
for i in range(w.shape[0]):
    for j in range(len(x1)):
        gdot[i] += w[i,j]*x1[j]
toc = time.perf_counter()
print("Time taken" + str(1000*(toc-tic)) + "ms.")



Time taken0.17240000306628644ms.
Time taken0.36860001273453236ms.
Time taken0.14459999511018395ms.
Time taken0.23170001804828644ms.


In [38]:
# using numpy functions for all these.
tic = time.perf_counter()
dot = np.dot(x1, x2) # of vectors
toc = time.perf_counter()
print("Time taken" + str(1000*(toc-tic)) + "ms.")

tic = time.perf_counter()
dot = np.outer(x1, x2)
toc = time.perf_counter()
print("Time taken" + str(1000*(toc-tic)) + "ms.")

tic = time.perf_counter()
dot = np.multiply(x1, x2) # element wise
toc = time.perf_counter()
print("Time taken" + str(1000*(toc-tic)) + "ms.")

tic = time.perf_counter()
dot = np.dot(w, x2) # general dot product
toc = time.perf_counter()
print("Time taken" + str(1000*(toc-tic)) + "ms.")


Time taken0.11439999798312783ms.
Time taken0.25850001838989556ms.
Time taken0.1162000116892159ms.
Time taken0.10090001160278916ms.


np.dot() performs a matrix-matrix or matrix-vector multiplication. This is different from np.multiply() and the * operator 

#### 2.1 Implement the L1 and L2 loss functions.

L1: summation of absolute loss between target and predicted values.

In [39]:
def L1(yhat, y):
    return np.sum(np.abs(y-yhat))

In [40]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print('L1 =' + str(L1(yhat, y)))


L1 =1.1


L2 loss

In [41]:
def L2(yhat, y):
    return np.sum((y-yhat)**2)

In [43]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("loss = " + str(L2(yhat, y)))

loss = 0.43
